#ifndef CUBETYPE_H
#define CUBETYPE_H

enum CubeType : unsigned char {
	AIR = 0,
	WATER = 1,
	GLASS = 2,
	BEDROCK = 3,
	DIRT = 4,
	GRASS_BLOCK = 5,
	GRASS_BLOCK_TOP = 6,
	STONE = 7,
	SNOW = 8,
	SAND = 9,
	COBBLESTONE = 10,
	ACACIA_LEAVES = 11,
	ACACIA_LOG = 12,
	ACACIA_LOG_TOP = 13,
	BIRCH_LEAVES = 14,
	BIRCH_LOG = 15,
	BIRCK_LOG_TOP = 16,
	CACTUS = 17,
	CACTUS_TOP = 18,
	DARK_OAK_LEAVES = 19,
	DARK_OAK_LOG = 20,
	DARK_OAK_LOG_TOP = 21,
	OAK_LEAVES = 22,
	OAK_LOG = 23,
	OAK_LOG_TOP = 24,
	SPRUCE_LEAVES = 25,
	SPRUCE_LOG = 26,
	SPRUCE_LOG_TOP = 27,
	DARK_GRASS_BLOCK = 28,
	DARK_GRASS_BLOCK_TOP = 29,

};

#endif // !CUBETYPE_H