#ifndef GRASSTYPE_H
#define GRASSTYPE_H

enum GrassType : unsigned char {
	AZURE_BLUET = 0,
	CORNFLOWER = 1,
	DANDELION = 2,
	GRASS = 3,
	LILAC_BOTTOM = 4,
	LILAC_TOP = 5,
	LILY_OF_THE_VALLEY = 6,
	ORANGE_TULIP = 7,
	PINK_TULIP = 8,
	POPPY = 9,
	RED_TULIP = 10,
	SUGAR_CANE = 11,
	TALL_GRASS_BOTTOM = 12,
	TALL_GRASS_TOP = 13,
	WHEAT_STAGE7 = 14,
	WHITE_TULIP = 15
};

#endif // !GRASSTYPE_H
