#ifndef GUITYPE_H
#define GUITYPE_H

enum GuiType : unsigned char {
	ACACIA_LEAVES_GUI = 0,
	ACACIA_LOG_GUI = 1,
	ANDESITE_GUI = 2,
	BEDROCK_GUI = 3,
	BIRCH_LEAVES_GUI = 4,
	BIRCH_LOG_GUI = 5,
	CACTUS_GUI = 6,
	COBBLESTONE_GUI = 7,
	DARK_OAK_LEAVES_GUI = 8,
	DARK_OAK_LOG_GUI = 9,
	DARKGRASS_GUI = 10,
	DIRT_GUI = 11,
	GLASS_GUI = 12,
	GRASS_GUI = 13,
	GRAVEL_GUI = 14,
	ICE_GUI = 15,
	OAK_LEAVES_GUI = 16,
	OAK_LOG_GUI = 17,
	OAK_PLANKS_GUI = 18,
	SAND_GUI = 19,
	SANDSTONE_GUI = 20,
	SNOW_GUI = 21,
	SPRUCE_LEAVES_GUI = 22,
	SPRUCE_LOG_GUI = 23,
	STONE_GUI = 24,
	DEFAULT_GUI = 25,

	HUD_ARROW_LEFT_SELECTED = 26,
	HUD_ARROW_LEFT_UNSELECTED = 27,
	HUD_ARROW_RIGHT_SELECTED = 28,
	HUD_ARROW_RIGHT_UNSELECTED = 29,
	HUD_HOTBAR = 30,
	HUD_MENUE = 31,
	HUD_PAGE_SELECTED = 32,
	HUD_PAGE_UNSELECTED = 33,
	HUD_BACKGROUND_SELECTED = 34,
	HUD_BACKGROUND_UNSELECTED_HOTBAR = 35,
	HUD_BACKGROUND_UNSELECTED_MENUE = 36,
	HUD_TRANSPARENT = 37
};

#endif // !GUITYPE_H
